name: firealarm_smart
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  outline_gradient_button: ^2.0.0+1
  intl: ^0.17.0
  flutter_blue: ^0.8.0
  oscilloscope: ^0.2.0+1

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/UbuntuRegular.ttf
          weight: 400
